#!/usr/bin/env python3

# set server timezone in UTC before time module imported

import os
import sys

sys.setrecursionlimit(99999)
LIB_PATH = os.path.join(os.path.dirname(__file__), '.', 'odoo-11.0')
sys.path.append(LIB_PATH)

__import__('os').environ['TZ'] = 'UTC'
# __import__('pkg_resources').declare_namespace('odoo.addons')

from tools import oegun

oegun.patch()

import odoo

if __name__ == "__main__":
    odoo.cli.main()
